silverstripe/silverstripe-reports

README.md

I assumed the module wasn't working, but it turns out I just had no report to show.

Added note about visibility of reports

---

code/ReportAdmin.php

see https://github.com/silverstripe/silverstripe-framework/pull/4706

FIX: HtmlEditorConfig should be using content_css

---

.travis.yml

Fixing travis config for 3 branch

Added standard Travis config

---

code/Report.php

... checks for ADMIN / CMS_ACCESS_ReportAdmin (from ReportAdmin)
fixes #13

FIX: SS_Report canView should check permissions

---

code/Report.php
tests/ReportTest.php

Fixes regressions in https://github.com/silverstripe-labs/silverstripe-reports/pull/14
Fixes https://github.com/silverstripe-labs/silverstripe-reports/issues/24

BUG Fix regressions is SS_Report::canView

---

code/SideReport.php

see https://github.com/silverstripe/silverstripe-cms/pull/1422

FIX Bad joining of links in reports

---

code/Report.php

How has this gone unfixed for so long?! :(
Before:
After:
/cc @clarkepaul

Remove triple report titles

---

code/Report.php
tests/ReportTest.php

FIX No longer hardcoding admin links

---

tests/ReportTest.php

ReportTest needs the database, if run in isolation these tests will fail.

ReportTest needs the database

---

code/Report.php
code/ReportAdmin.php
tests/ReportTest.php

Reports PR for https://github.com/silverstripe/silverstripe-framework/pull/5734

API Apply SilverStripe\ORM namespace

---

code/Report.php
code/ReportAdmin.php

To be merged with https://github.com/silverstripe/silverstripe-framework/pull/5741
To be merged after https://github.com/silverstripe-labs/silverstripe-reports/pull/33

API Apply SilverStripe\Security namespace

---

code/ReportAdmin.php

Required for https://github.com/silverstripe/silverstripe-framework/pull/5796

Fix ReportAdmin::Link() not returning correct home url

---

code/Report.php

Depends upon: silverstripe/silverstripe-framework#3274

FIX Use new admin_url

---

code/Report.php
tests/ReportTest.php

Fixes https://github.com/silverstripe/silverstripe-cms/issues/1183

BUG Fix incorrect url manipulation

---

code/Report.php
code/ReportAdmin.php

Substitute fix for code removed from https://github.com/silverstripe/silverstripe-framework/pull/5854#issuecomment-236487239 (for context).
However, this PR doesn't depend on that PR. :)

BUG Fix broken form actions on parent and nested gridfields

---

code/Report.php

See https://github.com/silverstripe/silverstripe-cms/issues/1572
Also remove unused reports

API Update for SilverStripe\CMS namespace

---

code/Report.php
code/ReportAdmin.php
templates/Includes/ReportAdmin_Content.ss

See https://github.com/silverstripe/silverstripe-framework/issues/5878
Add in new fix for namespaced reports.

Namespace Admin module

---

.upgrade.yml
code/Report.php
code/ReportAdmin.php
code/ReportWrapper.php
code/SideReportWrapper.php
tests/ReportTest.php

Merge with https://github.com/silverstripe/silverstripe-framework/pull/5974

Rename SS_ prefixed classes

---

code/ReportAdmin.php
javascript/ReportAdmin.js

Remove custom reportAdmin css overrides

Alignment and spacing of main CMS panels

---

code/Report.php

Fix for position of filter action, added space below action.
After:

Add spacing below filter action

---

templates/SilverStripe/Reports/Includes/ReportAdmin_Content.ss

Description https://github.com/silverstripe/silverstripe-framework/issues/6012
Requires https://github.com/silverstripe/silverstripe-framework/pull/6155
and https://github.com/silverstripe/silverstripe-cms/pull/1638

Replace Layout CSS classes for flexbox classes

---

code/ReportAdmin.php

See https://github.com/silverstripe/silverstripe-framework/pull/6434
Replaces https://github.com/silverstripe/silverstripe-reports/pull/56

Refresh CMS UI buttons to new flat style and bootstrap classes

---

code/Report.php

Required for https://github.com/silverstripe/silverstripe-framework/pull/6558

BUG Fix missing default on _t(‘GridField.Filter’)

---

code/ReportAdmin.php

Required for https://github.com/silverstripe/silverstripe-framework/pull/6607

Remove unnecessary tinymce config

---

code/Report.php
code/ReportAdmin.php

Move Member::currentUser() to Security::getCurrentUser()

[WIP] Authenticator refactor

---

.travis.yml
code/Report.php
code/ReportAdmin.php
code/SideReport.php
composer.json
phpcs.xml.dist
tests/ReportTest.php
tests/ReportTest/FakeObject.php
tests/ReportTest/FakeTest.php
tests/ReportTest/FakeTest2.php
tests/ReportTest/FakeTestAbstract.php

Main issue: https://github.com/silverstripe/silverstripe-framework/issues/6681
See https://github.com/silverstripe/silverstripe-framework/pull/7037 for framework pull request

[WIP] Upgrade module for app object refactor

---

.travis.yml

Reference: https://github.com/silverstripe/silverstripe-installer/issues/181

Add PHP 7.1 and SS 3.6 build to Travis configuration

---

code/Report.php
code/ReportAdmin.php

Issue: https://github.com/silverstripe/silverstripe-framework/issues/5757

FIX namespaces in docs

---

_config.php
code/ReportAdmin.php

Relies on
https://github.com/silverstripe/silverstripe-framework/pull/7065

API: Remove REPORTS_DIR and its use.

---

code/Report.php
templates/SilverStripe/Reports/Includes/ReportAdmin_Content.ss

Fixes https://github.com/silverstripe/silverstripe-admin/issues/217

FIX toolbar title layout

---

templates/SilverStripe/Reports/Includes/ReportAdmin_Content.ss

Please see https://github.com/silverstripe/silverstripe-admin/issues/286 for more details

BUG align heading properly

---

code/Report.php

NEW Remove duplicated report heading

---

code/Report.php

Also adds a couple of missing PHPDoc annotations for IDE hints

NEW Use Injector to create new class instances and pass $params

---

templates/SilverStripe/Reports/Includes/ReportAdmin_Content.ss

Related issue https://github.com/silverstripe/silverstripe-reports/issues/109

FIX Apply missing class to report header.

---

.travis.yml

* https://github.com/silverstripeltd/product-issues/issues/177

Merge up 1.6 branch + update travis to target x-dev branches

---

code/Report.php
code/ReportWrapper.php

Issue: https://github.com/silverstripe/silverstripe-framework/issues/1915

ENH Replace E_USER_ERROR errors with exceptions

---

.travis.yml
composer.json
phpcs.xml.dist

Fixes https://travis-ci.com/github/silverstripe/silverstripe-reports/jobs/423658754
I copied the phpcs line from
https://github.com/silverstripe/silverstripe-travis-shared/blob/master/config/script/phpcs.yml

MNT Update how phpcs is called

---

composer.json
tests/ReportAdminTest.php

Issue https://github.com/silverstripe/silverstripe-framework/issues/10019

MNT Remove polyfill

---

code/Report.php
code/ReportAdmin.php
code/SideReportView.php

Issue https://github.com/silverstripe/silverstripe-framework/issues/10250

ENH PHP 8.1 compatibility
